name: Go Test Build and Deploy

on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.25.1
      
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -v -o chessbot ./cmd/bot

    - uses: actions/upload-artifact@v4
      with:
          name: chessbot-artifact
          path: ./chessbot

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: chessbot-artifact
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           source: ./chessbot
           target: "/home/${{ secrets.USERNAME }}/projects/sw-bot"

      - name: Start ChessBot Swahili  service and Reload Nginx
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           script: |
               cd  /home/${{ secrets.USERNAME }}/projects/sw-bot
               chmod +x chessbot
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl stop chessbot.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl start chessbot.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl reload nginx

 
